# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://test:1234@ac-fvulclr-shard-00-00.gaewwmr.mongodb.net:27017,ac-fvulclr-shard-00-01.gaewwmr.mongodb.net:27017,ac-fvulclr-shard-00-02.gaewwmr.mongodb.net:27017/myDatabase?ssl=true&replicaSet=atlas-515840-shard-0&authSource=admin&appName=MyApp
# or use MongoDB Atlas URI: spring.data.mongodb.uri=mongodb+srv://<user>:<password>@cluster.mongodb.net/train_bot

# Logging
logging.level.org.springframework.web=INFO

# RapidAPI Configuration
rapidapi.key=df6b242d91msh03a79fd5bef11bap1c3ad1jsn7d62fe944f77

# API Hub live endpoint configuration (RapidAPI - Indian Railway IRCTC)
apihub.base.url=https://indian-railway-irctc.p.rapidapi.com/api/trains-search/v1/train
apihub.host=indian-railway-irctc.p.rapidapi.com
apihub.api.key=${rapidapi.key}
